# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SocketIoRealmSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'Socket.IO-Client-Swift', '~> 8.3.2' # Or latest version
    pod 'RealmSwift'
    
end
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
